apiVersion: v1
kind: Service
metadata:
  name: sub-chart-svc
  labels:
    app: sub-chart
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spk-subchart.selectorLabels" . | nindent 4 }}
